select 
    `Row ID` as row_id,
    `Order ID` as order_id,
    `Order date` as order_date,
    `Ship Date` as ship_date,
    `Ship Mode` as ship_mode,
    `Customer ID` as customer_id,
    `Customer Name` as customer_name,
    Segment as segment,
    `Postal Code` as postal_code,
    City as city,
    State as state,
    Country as country,
    Region as region,
    Market as market,
    `Product ID` as product_id,
    Category as category,
    `Sub-Category` as sub_category,
    `Product Name` as product_name,
    SAFE_CAST(`Sales` as float64) as sales,
    SAFE_CAST(Quantity as int64) as quantity,
    SAFE_CAST(Discount as float64) as discount,
    SAFE_CAST(Profit as float64) as profit,
    SAFE_CAST(`Shipping Cost` as float64) as shipping_cost,
    `Order Priority` as order_priority
from {{ source('raw', 'sales_raw_data') }}